*** Settings ***
Documentation     common settings for SharePoint
# Resource        ${EXECDIR}/resources/environments/${ENV}.resource
# Resource        ${EXECDIR}/resources/users/${USER}.resource

*** Variables ***
${SHAREPOINT_USERNAME} =    ${USER}
${SHAREPOINT_BASE_URL} =    http://groupportal2016-qa.sanlam.co.za
${SITE_REL_URL} =    /GIT/GIT_ProjectGov/SBITA
${ROOT_FOLDER_REL_URL} =    Shared Documents
